---
- name: Setup CI/CD Machines
  hosts: all
  become: yes

  tasks:
    - name: Update system
      apt:
        update_cache: yes

    - name: Install Java 21
      apt:
        name: openjdk-21-jdk
        state: present
